/*
 * Classical Chinese hexagram characters (卦名), indexed by King Wen number (1..64).
 * Traditional forms, consistent with the traditional Chinese used elsewhere in the
 * oracle (e.g. the QMDJ 節氣 / 八門 labels). Kept as a small standalone map — rather
 * than a field on every corpus entry — so index.html, the reference grid, and future
 * print/draw views can all share it without touching the 170 KB hybrid corpus.
 * Auto-checked by test/hexagram-chinese.test.ts.
 */
(function attachHexagramChinese() {
  window.hexagramChinese = {
    "1": "乾",
    "2": "坤",
    "3": "屯",
    "4": "蒙",
    "5": "需",
    "6": "訟",
    "7": "師",
    "8": "比",
    "9": "小畜",
    "10": "履",
    "11": "泰",
    "12": "否",
    "13": "同人",
    "14": "大有",
    "15": "謙",
    "16": "豫",
    "17": "隨",
    "18": "蠱",
    "19": "臨",
    "20": "觀",
    "21": "噬嗑",
    "22": "賁",
    "23": "剝",
    "24": "復",
    "25": "無妄",
    "26": "大畜",
    "27": "頤",
    "28": "大過",
    "29": "坎",
    "30": "離",
    "31": "咸",
    "32": "恆",
    "33": "遯",
    "34": "大壯",
    "35": "晉",
    "36": "明夷",
    "37": "家人",
    "38": "睽",
    "39": "蹇",
    "40": "解",
    "41": "損",
    "42": "益",
    "43": "夬",
    "44": "姤",
    "45": "萃",
    "46": "升",
    "47": "困",
    "48": "井",
    "49": "革",
    "50": "鼎",
    "51": "震",
    "52": "艮",
    "53": "漸",
    "54": "歸妹",
    "55": "豐",
    "56": "旅",
    "57": "巽",
    "58": "兌",
    "59": "渙",
    "60": "節",
    "61": "中孚",
    "62": "小過",
    "63": "既濟",
    "64": "未濟"
  };
})();
